---
title: "Protein Visualisation Workshop"
subtitle: "Protein visualisation workshop for MIPS, February 02-03, 2023."
---

### Before the Workshop
Ensure you have downloaded and installed the latest Blender ([currently 3.5.1](https://www.blender.org/download/)), as well as downloaded and installed the latest [Molecular Nodes](https://github.com/BradyAJohnston/MolecularNodes/releases). Instructions can be followed on the [Installation page](https://bradyajohnston.github.io/MolecularNodes/installation.html). If you are on an M1 or M2 Mac, the installation instructions are slightly more complex. Try your best to follow them and get it working but I can help out first thing on the day if you get stuck.

### What to Bring
If you have access to more than one laptop, the most powerful laptop you can get your hands on. Blender is well optimised to run even on older and less powerful computers, but the more powerful the computer, the easier your journey will be.

- Laptop 
  - the more powerful the better (specifically GPU)
- Power cable
  - you **WILL** run out of battery otherwise
- External 3-button mouse 
  - not a _requirement_, but will make working in Blender easier

### Workshop Outline

1. Introduction to Blender
- Blender workspaces
- Creating a basic 3D scene
- Using materials
- Rendering a basic image

2. Downloading Structures from the PDB
- Using Molecular Nodes to Download Structures
- Change Styles
- Use basic selection math to combine styles

3. Rendering a Nice Molecule
- Set up lighting, camera and materials
- Rendering different resolutions and speeding up your rendering

4. Animations in Molecular Nodes
- Wiggling Atoms
- Importing multie-frame PDBs
- Importing MD trajectories

5. Rendering Animations
- Setting up camera
- Render settings

7. Showing some animations

8. Recap of the first day / and what can be done

9. More on molecular nodes and what people want to play around with. 
